# Localized messages for the DTE Engine. Messages here give 
# the text of Design Engine exceptions.

###########################################################
#for test only
Error.Msg001={1} に {0} が見つかりません。

###########################################################

#load data engine factory exception
load.factory.error=データアダプタのファクトリを読み込めません。

context.null.error=データコンテキストは NULL にできません。
context.invalidDesigntimeMethod=ReportContext メソッド [{0}] は、実行時にしか使用できません。

adaptor.invalid.mode=データアダプタのモード値 {0} が無効です。
invalid.cache.option=データアダプタのオプション値 {0} が無効です。

datasource.null.error=Failed to find out data source of data set "{0}".
datasource.exid.error=データソース定義 {0} に拡張 ID がありません。

datasethandle.null.error=DataSetHandle は NULL にできません。
datasethandle.invalidColumnIndex=列のインデックスが無効です。
adapter.invalid.datetimetype=日時型 "{0}" が無効です。
adapter.invalid.aggregationfunctionname=The aggregation function {0} is invalid.

invalid.datetime.value=日時の値 "{0}" が無効です。
missing.join.condition=ファクトテーブルとディメンジョン "{0}" の間のジョイン条件がありません。
exception.error=処理中に例外が発生しました。詳しくは次のメッセージを参照してください :
invalid.level.expression=レベル名 "{0}" が見つかりません。
invalid.measure.expression=メジャー "{0}" の式は null にできません。
invalid.data.type=データ型が無効です : {0} 

cube.error.createhierarchy=階層 {0} の作成中にエラーが発生しました。
cube.error.createdimension=ディメンジョン {0} の作成中にエラーが発生しました。
cube.error.createmeasure=メジャー要素の作成中にエラーが発生しました。
